# An incomplete base Docker image for running JupyterHub
#
# Add your configuration to create a complete derivative Docker image.
#
# Include your configuration settings by starting with one of two options:
#
# Option 1:
#
FROM jupyterhub/jupyterhub:latest
#
# And put your configuration file jupyterhub_config.py in /srv/jupyterhub/jupyterhub_config.py.
#
# Option 2:
#
# Or you can create your jupyterhub config and database on the host machine, and mount it with:
#
# docker run -v $PWD:/srv/jupyterhub -t jupyterhub/jupyterhub
#
# NOTE
# If you base on jupyterhub/jupyterhub-onbuild
# your jupyterhub_config.py will be added automatically
# from your docker directory.

FROM debian:jessie
MAINTAINER Colin Higgins <colin@svds.com>

# install nodejs, utf8 locale
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get -y install npm nodejs nodejs-legacy wget locales git &&\
    /usr/sbin/update-locale LANG=C.UTF-8 && \
    locale-gen C.UTF-8 && \
    apt-get remove -y locales && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
ENV LANG C.UTF-8

# install Python with conda
RUN wget -q https://repo.continuum.io/miniconda/Miniconda3-4.0.5-Linux-x86_64.sh -O /tmp/miniconda.sh  && \
    echo 'a7bcd0425d8b6688753946b59681572f63c2241aed77bf0ec6de4c5edc5ceeac */tmp/miniconda.sh' | shasum -a 256 -c - && \
    bash /tmp/miniconda.sh -f -b -p /opt/conda && \
    /opt/conda/bin/conda install --yes python=3.5 sqlalchemy tornado jinja2 traitlets requests pip && \
    /opt/conda/bin/pip install --upgrade pip && \
    rm /tmp/miniconda.sh
ENV PATH=/opt/conda/bin:$PATH

# install js dependencies
RUN npm install -g configurable-http-proxy && rm -rf ~/.npm

ADD . /src/jupyterhub
WORKDIR /src/jupyterhub

RUN ls > files.txt

RUN python setup.py js && pip install . && \
    rm -rf $PWD ~/.cache ~/.npm

RUN mkdir -p /srv/jupyterhub/
WORKDIR /srv/jupyterhub/
EXPOSE 8000

RUN conda install -y notebook
RUN openssl req  -batch -x509 -nodes -days 365 -newkey rsa:1024 -keyout jupyterhub.key -out jupyterhub.crt
RUN echo -e "c.JupyterHub.admin_access = True\nc.JupyterHub.admin_users = {'colin'}\nc.JupyterHub.ssl_cert = '/srv/jupyterhub/jupyterhub.crt'\nc.JupyterHub.ssl_key = '/srv/jupyterhub/jupyterhub.key'" > jupyterhub_config.py

RUN apt-get -y update
RUN apt-get -y install vim
RUN conda create -n py2 -y python=2 ipykernel
RUN conda run -n py2 -- ipython kernel install
RUN adduser colin
RUN echo "colin:svds" | chpasswd
RUN pip install psutil
RUN git clone https://github.com/ipython-contrib/IPython-notebook-extensions.git
RUN IPython-notebook-extensions/setup.py install

RUN cp -r /root/.local/share/jupyter/templates /home/colin/.local/share/jupyter/templates
RUN cp -r /root/.local/share/jupyter/extensions /home/colin/.local/share/jupyter/extensions
RUN cp -r /root/.local/share/jupyter/nbextensions /home/colin/.local/share/jupyter/nbextensions
RUN echo "from jupyter_core.paths import jupyter_config_dir, jupyter_data_dir \n import os.path \n import sys \n \n sys.path.append(os.path.join(jupyter_data_dir(), 'extensions')) \n \n c = get_config() \n \n c.NotebookApp.extra_template_paths = [os.path.join(jupyter_data_dir(), 'templates') ] \n c.NotebookApp.server_extensions = ['nbextensions'] \n" > /root/.jupyter/jupyter_notebook_config.py
RUN cp /root/.jupyter/jupyter_notebook_config.py /home/colin/.jupyter/jupyter_notebook_config.py


LABEL org.jupyter.service="jupyterhub"

CMD ["jupyterhub"]
